

import 'package:flutter/material.dart';
import 'package:swalis/client/data%20classes/product.dart';

var productList = [
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/gel_douche.png",
      'Nouveautés',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/capillaire.png",
      'Cappillaire',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/hygiene.png",
      'Phares',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/soin.png",
      'Cappillaire',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/gel_douche.png",
      'Nouveautés',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/soin.png",
      'Hygiene',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/capillaire.png",
      'Phares',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/gel_douche.png",
      'Phares',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/soin.png",
      'Phares',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/hygiene.png",
      'Cappillaire',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/gel_douche.png",
      'Nouveautés',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/hygiene.png",
      'Hygiene',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/soin.png",
      'Soin',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/capillaire.png",
      'Phares',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/gel_douche.png",
      'Soin',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/capillaire.png",
      'Nouveautés',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/gel_douche.png",
      'Phares',
    ),
  Product(
      0,
      'Gel Douche Plaisir',
      240.00,
      'Sa formule enrichie à l’extrait de grenade et son parfum fruité aux accords pétillants et gourmands, vitalise vos sens pour le plaisir d’une douche détendue.',
      "assets/hygiene.png",
      'Soin',
    ),
];